---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: nightscout
  namespace: nightscout
spec:
  interval: 30m
  chart:
    spec:
      chart: ./
      sourceRef:
        kind: GitRepository
        name: helm-nightscout
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    global:
      imagePullSecrets:
        - dockerhub-pull-secret

    image:
      repository: nightscout/cgm-remote-monitor
      tag: "15.0.3"

    replicaCount: 1

    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi

    service:
      type: ClusterIP
      port: 1337

    ingress:
      enabled: true
      className: "istio"
      annotations:
        cert-manager.io/cluster-issuer: "selfsigned-issuer"
      hosts:
        - host: nightscout.homelab.local
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: nightscout-tls
          hosts:
            - nightscout.homelab.local

    networkPolicy:
      enabled: true
      ingress:
        enabled: true
        namespaceSelector:
          matchLabels:
            name: istio-system
      egress:
        enabled: true
        allowExternal: true

    # MongoDB is now integrated into the chart
    # Secrets are auto-generated
    mongodb:
      enabled: true
      image:
        tag: "latest"
      auth:
        enabled: true
        database: nightscout
        username: nightscout
        password: "nightscoutmongodbpassword"  # Static password for consistent auth
      persistence:
        enabled: true
        size: 8Gi
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 250m
          memory: 256Mi

    startupProbe:
      enabled: true
      probe:
        httpGet:
          path: /api/v1/status
          port: http
          scheme: HTTP
        initialDelaySeconds: 30
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 60  # 60 * 10s = 10 minutes max startup time

    livenessProbe:
      httpGet:
        path: /api/v1/status
        port: http
        scheme: HTTP
      initialDelaySeconds: 60
      periodSeconds: 30
      timeoutSeconds: 10
      failureThreshold: 3

    readinessProbe:
      httpGet:
        path: /api/v1/status
        port: http
        scheme: HTTP
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3

    nightscout:
      # MongoDB URI and API secret will be auto-generated
      # Leave commented to use integrated MongoDB and auto-generated secret

      baseUrl: "https://nightscout.gluk0.sh"

      security:
        insecureUseHttp: true  # TLS terminated at Cloudflare tunnel

      enable:
        - careportal
        - boluscalc
        - food
        - rawbg
        - iob
        - cob
        - bwp
        - cage
        - sage
        - iage
        - bage
        - basal
        - ar2
        - treatmentnotify

      auth:
        defaultRoles: "readable"

      alarms:
        types: "simple"
