---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: media-gateway
  namespace: media
spec:
  selector:
    istio: ilb-gateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "jellyfin.homelab.local"
    - "qbittorrent.homelab.local"
    - "prowlarr.homelab.local"
    - "sonarr.homelab.local"
    - "radarr.homelab.local"
