---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: media-default-deny
  namespace: media
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: jellyfin-policy
  namespace: media
spec:
  podSelector:
    matchLabels:
      app: jellyfin
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 8096
  egress:
  - {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: qbittorrent-policy
  namespace: media
spec:
  podSelector:
    matchLabels:
      app: qbittorrent
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 8080
  egress:
  - {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: debrid-media-manager-policy
  namespace: media
spec:
  podSelector:
    matchLabels:
      app: debrid-media-manager
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 3000
  egress:
  - {}
