---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor
spec:
  interval: 30m
  chart:
    spec:
      chart: harbor
      version: '1.x'
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: flux-system
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    expose:
      type: loadBalancer
      tls:
        enabled: false
        certSource: auto
        auto:
          commonName: ""
        secret:
          secretName: ""
          notarySecretName: ""
      loadBalancer:
        name: harbor
        IP: ""
        ports:
          httpPort: 80
          httpsPort: 443
        annotations: {}
        sourceRanges: []

    externalURL: http://harbor.local

    internalTLS:
      enabled: false

    ipFamily:
      ipv4:
        enabled: true
      ipv6:
        enabled: false

    persistence:
      enabled: true
      resourcePolicy: "keep"
      persistentVolumeClaim:
        registry:
          existingClaim: ""
          storageClass: ""
          subPath: ""
          accessMode: ReadWriteOnce
          size: 20Gi
          annotations: {}
        chartmuseum:
          existingClaim: ""
          storageClass: ""
          subPath: ""
          accessMode: ReadWriteOnce
          size: 5Gi
          annotations: {}
        jobservice:
          jobLog:
            existingClaim: ""
            storageClass: ""
            subPath: ""
            accessMode: ReadWriteOnce
            size: 1Gi
            annotations: {}
        database:
          existingClaim: ""
          storageClass: ""
          subPath: ""
          accessMode: ReadWriteOnce
          size: 5Gi
          annotations: {}
        redis:
          existingClaim: ""
          storageClass: ""
          subPath: ""
          accessMode: ReadWriteOnce
          size: 1Gi
          annotations: {}
        trivy:
          existingClaim: ""
          storageClass: ""
          subPath: ""
          accessMode: ReadWriteOnce
          size: 5Gi
          annotations: {}
      imageChartStorage:
        disableredirect: false
        type: filesystem
        filesystem:
          rootdirectory: /storage
          maxthreads: 100

    existingSecretAdminPassword: ""
    existingSecretAdminPasswordKey: HARBOR_ADMIN_PASSWORD

    harborAdminPassword: "Harbor12345"

    secretKey: "not-a-secure-key"

    proxy:
      httpProxy: ""
      httpsProxy: ""
      noProxy: 127.0.0.1,localhost,.local,.internal
      components:
        - core
        - jobservice
        - trivy

    enableMigrateHelmHook: false

    updateStrategy:
      type: RollingUpdate

    logLevel: info

    portal:
      replicas: 1
      revisionHistoryLimit: 10
      resources:
        requests:
          memory: 256Mi
          cpu: 100m
      nodeSelector:
        kubernetes.io/hostname: k8s-worker-01
      tolerations: []
      affinity: {}
      priorityClassName: ""
      serviceAccountName: ""
      automountServiceAccountToken: false
      podAnnotations: {}
      podLabels: {}

    core:
      replicas: 1
      revisionHistoryLimit: 10
      startupProbe:
        enabled: true
        initialDelaySeconds: 10
      resources:
        requests:
          memory: 256Mi
          cpu: 100m
      nodeSelector:
        kubernetes.io/hostname: k8s-worker-01
      tolerations: []
      affinity: {}
      priorityClassName: ""
      serviceAccountName: ""
      automountServiceAccountToken: false
      podAnnotations: {}
      podLabels: {}
      secret: ""
      secretName: ""
      xsrfKey: ""
      configureUserSettings: ""
      quotaUpdateProvider: db

    jobservice:
      replicas: 1
      revisionHistoryLimit: 10
      maxJobWorkers: 10
      jobLoggers:
        - file
      loggerSweeperDuration: 14
      startupProbe:
        enabled: true
        initialDelaySeconds: 30
      resources:
        requests:
          memory: 256Mi
          cpu: 100m
      nodeSelector:
        kubernetes.io/hostname: k8s-worker-01
      tolerations: []
      affinity: {}
      priorityClassName: ""
      serviceAccountName: ""
      automountServiceAccountToken: false
      podAnnotations: {}
      podLabels: {}
      secret: ""

    registry:
      replicas: 1
      revisionHistoryLimit: 10
      registry:
        replicas: 1
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
        nodeSelector:
          kubernetes.io/hostname: k8s-worker-01
        tolerations: []
        affinity: {}
        priorityClassName: ""
        podAnnotations: {}
        podLabels: {}
      controller:
        replicas: 1
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
        nodeSelector:
          kubernetes.io/hostname: k8s-worker-01
        tolerations: []
        affinity: {}
        priorityClassName: ""
        podAnnotations: {}
        podLabels: {}
      serviceAccountName: ""
      automountServiceAccountToken: false
      relativeurls: false
      credentials:
        username: "harbor_registry_user"
        password: "harbor_registry_password"
        existingSecret: ""
        htpasswd: ""
      middleware:
        enabled: false
        type: cloudFront
        cloudFront:
          baseurl: example.cloudfront.net
          keypairid: KEYPAIRID
          duration: 3000s
          ipfilteredby: none
          privateKeySecret: "my-secret"
      upload_purging:
        enabled: true
        age: 168h
        interval: 24h
        dryrun: false

    trivy:
      enabled: true
      replicas: 1
      revisionHistoryLimit: 10
      gitHubToken: ""
      skipUpdate: false
      skipJavaDBUpdate: false
      offlineScan: false
      insecure: false
      resources:
        requests:
          cpu: 200m
          memory: 512Mi
        limits:
          cpu: 1
          memory: 1Gi
      nodeSelector:
        kubernetes.io/hostname: k8s-worker-01
      tolerations: []
      affinity: {}
      priorityClassName: ""
      serviceAccountName: ""
      automountServiceAccountToken: false
      podAnnotations: {}
      podLabels: {}

    database:
      type: internal
      internal:
        image:
          repository: goharbor/harbor-db
          tag: v2.11.0
        initContainerImage:
          repository: goharbor/harbor-db
          tag: v2.11.0
        password: "changeit"
        shmSizeLimit: 512Mi
        livenessProbe:
          timeoutSeconds: 1
        readinessProbe:
          timeoutSeconds: 1
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
        nodeSelector:
          kubernetes.io/hostname: k8s-worker-01
        tolerations: []
        affinity: {}
        priorityClassName: ""
        serviceAccountName: ""
        automountServiceAccountToken: false
        podAnnotations: {}
        podLabels: {}
      external:
        host: "192.168.0.1"
        port: "5432"
        username: "user"
        password: "password"
        coreDatabase: "registry"
        existingSecret: ""
        sslmode: "disable"
      maxIdleConns: 100
      maxOpenConns: 900
      podAnnotations: {}
      podLabels: {}

    redis:
      type: internal
      internal:
        image:
          repository: goharbor/redis-photon
          tag: v2.11.0
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
        nodeSelector:
          kubernetes.io/hostname: k8s-worker-01
        tolerations: []
        affinity: {}
        priorityClassName: ""
        serviceAccountName: ""
        automountServiceAccountToken: false
        podAnnotations: {}
        podLabels: {}
      external:
        addr: "192.168.0.2:6379"
        sentinelMasterSet: ""
        coreDatabaseIndex: "0"
        jobserviceDatabaseIndex: "1"
        registryDatabaseIndex: "2"
        trivyAdapterIndex: "5"
        password: ""
        existingSecret: ""

    metrics:
      enabled: false
      core:
        path: /metrics
        port: 8001
      registry:
        path: /metrics
        port: 8001
      jobservice:
        path: /metrics
        port: 8001
      exporter:
        path: /metrics
        port: 8001
      serviceMonitor:
        enabled: false
        additionalLabels: {}
        interval: ""
        metricRelabelings: []
        relabelings: []

    trace:
      enabled: false
      provider: jaeger
      sample_rate: 1
      jaeger:
        endpoint: http://hostname:14268/api/traces
        username: ""
        password: ""
        agent_host: hostname
        agent_port: 6831
      otel:
        endpoint: hostname:4318
        url_path: /v1/traces
        compression: false
        insecure: true
        timeout: 10s

    cache:
      enabled: false
      expireHours: 24

    chartmuseum:
      enabled: true
      absoluteUrl: false
      revisionHistoryLimit: 10
      resources:
        requests:
          memory: 256Mi
          cpu: 100m
      nodeSelector:
        kubernetes.io/hostname: k8s-worker-01
      tolerations: []
      affinity: {}
      priorityClassName: ""
      serviceAccountName: ""
      automountServiceAccountToken: false
      podAnnotations: {}
      podLabels: {}
