---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 30m
  chart:
    spec:
      chart: ingress-nginx
      version: '4.x'  # Automatically use latest 4.x version
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      interval: 12h
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    controller:
      # Set the ingress class
      ingressClassResource:
        default: true

      # Service configuration
      service:
        type: LoadBalancer
        # Uncomment and configure if you need a specific LoadBalancer IP
        # loadBalancerIP: "192.168.1.100"

      # Resource limits (adjust based on your needs)
      resources:
        requests:
          cpu: 100m
          memory: 90Mi
        limits:
          memory: 256Mi

      # Enable metrics for monitoring
      metrics:
        enabled: true
        serviceMonitor:
          enabled: false  # Set to true if you have Prometheus Operator

      # Additional configuration
      config:
        # Customize nginx config here
        # Example: use-forwarded-headers: "true"
