---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio-system
spec:
  interval: 30m
  chart:
    spec:
      chart: base
      version: 1.24.0
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      interval: 12h
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
