---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kiali-server
  namespace: istio-system
spec:
  interval: 30m
  chart:
    spec:
      chart: kiali-server
      version: 1.93.0
      sourceRef:
        kind: HelmRepository
        name: kiali
        namespace: flux-system
      interval: 12h
  dependsOn:
    - name: istiod
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    auth:
      strategy: anonymous
    deployment:
      accessible_namespaces:
      - "**"
    external_services:
      istio:
        root_namespace: istio-system
      prometheus:
        url: "http://prometheus-server.monitoring:80"
    server:
      web_root: /kiali
    service:
      type: LoadBalancer
