---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 30m
  chart:
    spec:
      chart: ingress-nginx
      version: '4.x'  # Automatically use latest 4.x version
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      interval: 12h
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    controller:
      ingressClassResource:
        default: true
      service:
        type: LoadBalancer
        loadBalancerIP: "10.20.0.50"
      resources:
        requests:
          cpu: 100m
          memory: 90Mi
        limits:
          memory: 256Mi
      metrics:
        enabled: true
        serviceMonitor:
          enabled: false
