---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gateway-api
  namespace: gateway-system
spec:
  interval: 30m
  chart:
    spec:
      chart: gateway-api
      version: '1.2.x'
      sourceRef:
        kind: HelmRepository
        name: gateway-api
        namespace: flux-system
      interval: 12h
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
